# Configuración Nginx INSEGURA (Fase A)
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/netops-portal;
    index index.html;
    server_name _;
    
    # ⚠️ PELIGRO: Sin hardening, server_tokens on por defecto
    # ⚠️ PELIGRO: Archivos ocultos (.git) expuestos

    location / {
        try_files $uri $uri/ =404;
    }
}
