# ═══════════════════════════════════════════════════════════════
# Configuración Nginx — NetOps Secure Execution Portal
# Laboratorio 3 FDSI | Grupo G06
# ═══════════════════════════════════════════════════════════════

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/netops-portal;
    index index.html;
    server_name _;

    # ── Hardening inicial (Blue Team) ──────────────────────────
    server_tokens off;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header Referrer-Policy "no-referrer" always;
    autoindex off;

    # ── Rutas ──────────────────────────────────────────────────
    location / {
        try_files $uri $uri/ =404;
    }

    # ── Bloquear archivos ocultos ──────────────────────────────
    location ~ /\. {
        deny all;
        return 403;
    }

    # ── Logs ───────────────────────────────────────────────────
    access_log /var/log/nginx/netops-access.log;
    error_log  /var/log/nginx/netops-error.log;
}
